In [2]:
import pandas as pd
import numpy as np

In [3]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

merged_file = PROJECT_ROOT / "data" / "processed" / "nepse_merged_historical_data.csv"


df = pd.read_csv(merged_file)

df.head()

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,symbol
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.0,0,ADBL
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.0,0,ADBL
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.0,0,ADBL
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.0,0,ADBL
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.0,0,ADBL

In [4]:
df.groupby("symbol").head(1).reset_index(drop=True).head(30)

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status,symbol
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.0,0,ADBL
1,2009-11-25,408.0,790.0,790.0,790.0,NaN,10.0,0.0,0,AHPC
2,2018-12-25,102.0,102.0,98.0,101.0,-0.98,590.0,58880.0,-1,AKJCL
3,2017-07-02,421.0,420.0,405.0,410.0,NaN,3952.0,1623186.0,0,AKPL
4,2010-06-13,226.0,233.0,223.0,226.0,NaN,13110.0,0.0,0,ALICL
5,2015-12-29,371.0,381.0,368.0,372.0,NaN,13555.0,5029450.0,0,API
6,2015-10-28,388.0,426.0,395.0,419.0,NaN,5200.0,2161590.0,0,BARUN
7,2011-06-26,386.0,400.0,393.0,400.0,NaN,44.0,17446.0,0,BFC
8,2016-11-20,675.0,688.0,638.0,655.0,NaN,77691.0,50652744.0,0,BOKL
9,2005-01-20,480.0,280.0,250.0,280.0,NaN,4230.0,0.0,0,BPCL
10,2013-05-19,153.0,154.0,150.0,150.0,NaN,16083.0,2429913.0,0,CBL
11,2014-06-18,336.0,338.0,320.0,323.0,NaN,34780.0,11519897.0,0,CCBL
12,2003-06-06,143.0,145.0,145.0,145.0,NaN,90.0,0.0,0,CFCL
13,2021-02-07,161.0,164.0,161.0,164.0,0.00,30.0,4860.0,0,CGH
14,2006-06-13,800.0,281.0,276.0,281.0,NaN,260950.0,0.0,0,CHCL
15,2021-07-05,625.0,669.0,620.0,654.0,5.31,51282.0,33328063.0,1,CHDC
16,2017-09-17,163.0,165.0,158.0,159.0,NaN,248.0,39778.0,0,CHL
17,2011-08-10,437.0,440.0,432.0,432.0,NaN,72.0,31184.0,0,CIT
18,2012-03-11,116.0,115.0,114.0,114.0,NaN,1410.0,160800.0,0,CORBL
19,2009-06-25,530.0,530.0,520.0,520.0,NaN,3760.0,0.0,0,CZBIL
20,2017-04-20,244.0,240.0,240.0,240.0,NaN,86.0,20640.0,0,DHPL
21,2011-05-26,992.0,973.0,973.0,973.0,NaN,91.0,88543.0,0,EBL
22,2008-03-26,630.0,630.0,630.0,630.0,NaN,20.0,0.0,0,EDBL
23,2011-06-05,132.0,134.0,128.0,128.0,NaN,810.0,105900.0,0,GBBL
24,2012-09-26,248.0,249.0,244.0,247.0,NaN,7227.0,1771727.0,0,GBIME
25,2013-07-29,108.0,106.0,106.0,106.0,NaN,446.0,47276.0,0,GFCL
26,2019-06-12,85.0,87.0,85.0,86.0,0.00,500.0,42780.0,0,GHL
27,2021-04-25,379.0,379.0,364.0,372.0,-3.63,20901.0,7720371.0,-1,GLH
28,2011-10-20,129.0,127.0,119.0,119.0,NaN,290.0,34710.0,0,GLICL
29,2012-06-25,273.0,268.0,268.0,268.0,NaN,100.0,26800.0,0,GMFIL

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265702 entries, 0 to 265701
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   published_date   265702 non-null  object
 1   open             265702 non-null  float64
 2   high             265702 non-null  float64
 3   low              265702 non-null  float64
 4   close            265702 non-null  float64
 5   per_change       265615 non-null  float64
 6   traded_quantity  265702 non-null  float64
 7   traded_amount    265702 non-null  float64
 8   status           265702 non-null  int64
 9   symbol           265702 non-null  object
dtypes: float64(7), int64(1), object(2)
memory usage: 20.3+ MB